# Contains all Settings for the Task
# Values for fields and definitions of directions

GOAL = "E"
PENALTY = "P"
FIELD = "F"
WALL = "O"

TYPES = [GOAL, PENALTY, FIELD, WALL]


NOMOVE = 0
UP = 1
RIGHT = 2
DOWN = 3
LEFT = 4

DIRECTIONS = [NOMOVE, UP, RIGHT, DOWN, LEFT]

NOMOVE_D = (0, 0)
UP_D = (-1, 0)
RIGHT_D = (0, 1)
DOWN_D = (1, 0)
LEFT_D = (0, -1)

DIRECTIONS_D = {NOMOVE: NOMOVE_D, UP: UP_D, RIGHT: RIGHT_D, DOWN: DOWN_D, LEFT: LEFT_D}

DIRECTION_SYMBOLS = {NOMOVE: "o", UP: '\u25b2', RIGHT: '>', DOWN: 'V', LEFT: '<'}

FIELD_PROB_NOMOVE = {NOMOVE: 1, UP: 0, RIGHT: 0, DOWN: 0, LEFT: 0}
FIELD_PROB_UP = {NOMOVE: 0, UP: 0.8, RIGHT: 0.1, DOWN: 0, LEFT: 0.1}
FIELD_PROB_RIGHT = {NOMOVE: 0, UP: 0.1, RIGHT: 0.8, DOWN: 0.1, LEFT: 0}
FIELD_PROB_DOWN = {NOMOVE: 0, UP: 0, RIGHT: 0.1, DOWN: 0.8, LEFT: 0.1}
FIELD_PROB_LEFT = {NOMOVE: 0, UP: 0.1, RIGHT: 0, DOWN: 0.1, LEFT: 0.8}

FIELD_PROBS = {NOMOVE: FIELD_PROB_NOMOVE, UP: FIELD_PROB_UP, RIGHT: FIELD_PROB_RIGHT, DOWN: FIELD_PROB_DOWN,
               LEFT: FIELD_PROB_LEFT}

GOAL_PROB_ANY = {NOMOVE: 1, UP: 0, RIGHT: 0, DOWN: 0, LEFT: 0}
GOAL_PROBS = {NOMOVE: GOAL_PROB_ANY, UP: GOAL_PROB_ANY, RIGHT: GOAL_PROB_ANY, DOWN: GOAL_PROB_ANY,
              LEFT: GOAL_PROB_ANY}
GOAL_REWARD = 1

PENALTY_PROB_ANY = {NOMOVE: 1, UP: 0, RIGHT: 0, DOWN: 0, LEFT: 0}
PENALTY_PROBS = {NOMOVE: PENALTY_PROB_ANY, UP: PENALTY_PROB_ANY, RIGHT: PENALTY_PROB_ANY, DOWN: PENALTY_PROB_ANY,
                 LEFT: PENALTY_PROB_ANY}
PENALTY_REWARD = -1

WALL_PROB_ANY = {NOMOVE: 1, UP: 0, RIGHT: 0, DOWN: 0, LEFT: 0}
WALL_PROBS = {NOMOVE: WALL_PROB_ANY, UP: WALL_PROB_ANY, RIGHT: WALL_PROB_ANY, DOWN: WALL_PROB_ANY,
              LEFT: WALL_PROB_ANY}
WALL_REWARD = 0

MOVEMENT_PROBS = {FIELD: FIELD_PROBS, GOAL: GOAL_PROBS, PENALTY: PENALTY_PROBS,
                  WALL: WALL_PROBS}

